---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx 
  annotations:
    created_by: "Farrukh"
    repo: "https://github.com"
spec:
  containers:
  - name: artemis
    image: farrukhsadykov/artemis:latest
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
      httpGet: null
      tcpSocket:
        port: 5000
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
      httpGet: null
      tcpSocket:
        port: 5000
