---
apiVersion: v1
kind: Namespace
metadata:
  name: artemis

---  
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: artemis
  namespace: artemis
  labels:
    app.kubernetes.io/name: artemis
spec:
  replicas: 1
  selector:             # dictates how to find the pod
    matchLabels:
      app.kubernetes.io/name: artemis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: artemis    # assigns the label to the pod
    spec:
      containers:
      - name: artemis
        image: farrukhsadykov/artemis:latest
     

---
apiVersion: v1
kind: Service
metadata:
  name: artemis
  namespace: artemis
spec:
  selector:
    app.kubernetes.io/name: artemis
  ports:
  - name: webserver
    protocol: TCP
    port: 80
    targetPort: 5000
  - name: secure-webserver
    protocol: TCP
    port: 443
    targetPort: 5443
  - name: secure-db
    protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  - 127.0.0.1/32
